const string = {
  comman: {
    Login: 'Login',
  },
  auth: {
    Create_your_account: 'Create your account',
    Create_Account: 'Create Account',
    Welcome_back: 'Welcome back!\nEnter your number',
    Continue: 'Continue',
    Continue_with_Email: 'Continue with Email',
    Continue_with_Facebook: 'Continue with Facebook',
    Continue_with_Google: 'Continue with Google',
    Already_joined: 'Already joined? ',
    Log_in: 'Log in',
    create_account: 'Hi!\nLet’s create your account.',
    First_Name: 'First Name',
    Last_name: 'Last Name',
    Email: 'Email',
    Set_a_password: 'Set a password',
    Password: 'Password',
    Phone: 'Phone',
    OTP_Code: 'OTP Code',
    no_account: 'If you don’t have an account, ',
    create_one: 'create one.',
    Confirm_Password: 'Confirm Password',
    password_length: 'Your password should be at least 8 character long',
    whats_phone: 'What’s your phone number?',
    whats_phone_content: 'I need your phone number to identify you.',
    Enter_verification_code: 'Enter verification code',
    Sent_to: 'Sent to ',
  },
  local_info: {
    Local_Information: 'Local Information',
    Search: 'Search',
    Cancel: 'Cancel',
    Home: 'Home',
    Work: 'Work',
    Add_place: 'Add place',
    Direction: 'Direction',
    Share: 'Share',
  },
};

export default string;
